Fix indent,format, Fix shellcheck warn

diff --git a/note b/note
--- a/note
+++ b/note
@@ -2,82 +2,82 @@
 
 TODO_NOTES_DIR=$TODO_DIR/notes
 TODO_NOTE_TAG="note"
-TODO_NOTE_TEMPLATE="XXX"
 TODO_NOTE_EXT=${TODO_NOTE_EXT:-.txt}
 TODO_NOTE_ARCHIVE="$TODO_NOTES_DIR/archive$TODO_NOTE_EXT"
 
 usage() {
-    echo "    $(basename $0) add|a ITEM#"
-    echo "      Adds a note to the task on line ITEM#."
-    echo "    $(basename $0) edit|e ITEM#|archive|a"
-    echo "      Opens in EDITOR the note related with the task on line ITEM# or the notes archive."
-    echo "    $(basename $0) show|s ITEM#|archive|a"
-    echo "      Shows the note related with the task on line ITEM# or the notes archive."
+  echo "    $(basename "$0") add|a ITEM#"
+  echo "      Adds a note to the task on line ITEM#."
+  echo "    $(basename "$0") edit|e ITEM#|archive|a"
+  echo "      Opens in EDITOR the note related with the task on line ITEM# or the notes archive."
+  echo "    $(basename "$0") show|s ITEM#|archive|a"
+  echo "      Shows the note related with the task on line ITEM# or the notes archive."
 }
 
 getnotenamefromnumber() {
-    # Parameters:
-    #    $1: task number
-    # Preconditions:
-    #   $errmsg contains usage message.
-    # Postcondition:
-    #     $notename contains note name, if task has note.
-    #     $item contains the task name
+  # Parameters:
+  #   $1: task number
+  # Preconditions:
+  #   $errmsg contains usage message.
+  # Postcondition:
+  #   $notename contains note name, if task has note.
+  #   $item contains the task name
 
-    item="$1"
+  item="$1"
 
-    getTodo "$item"
-    getnotenamefromtext "$todo"
+  getTodo "$item"
+  # shellcheck disable=SC2154
+  getnotenamefromtext "$todo"
 }
 
 getnotenamefromtext() {
-    # Parameters: $1: task text
-    # Preconditions: none
-    # Postcondition:
-    #     $notename contains note name, if task has note.
+  # Parameters: $1: task text
+  # Preconditions: none
+  # Postcondition:
+  #   $notename contains note name, if task has note.
 
-    notename=$(echo "$1" | grep -o " $TODO_NOTE_TAG:[^ .]*${TODO_NOTE_EXT}" | grep -o "[^:]*${TODO_NOTE_EXT}")
+  notename=$(echo "$1" | grep -o " $TODO_NOTE_TAG:[^ .]*${TODO_NOTE_EXT}" | grep -o "[^:]*${TODO_NOTE_EXT}")
 }
 
 editnote() {
-    # Parameter:: $1: Path of the file to edit
-    # Preconditions: none
-    # Postcondition: none
-    if [ "$EDITOR" ]
-    then
-        $EDITOR "$1"
-    else
-        echo The EDITOR environment variable is not set.
-    fi
+  # Parameter:: $1: Path of the file to edit
+  # Preconditions: none
+  # Postcondition: none
+  if [ "$EDITOR" ]
+  then
+    $EDITOR "$1"
+  else
+    echo The EDITOR environment variable is not set.
+  fi
 
 }
 
 getnotefilepath () {
-    # Parameter:: $1: Task number or reference to file
-    # Preconditions:
-    # Postcondition: $notefilepath contains the path of the file to edit or show
+  # Parameter:: $1: Task number or reference to file
+  # Preconditions:
+  # Postcondition: $notefilepath contains the path of the file to edit or show
 
-    item="$1"
+  item="$1"
 
-    if [[ "$item" ]] && [[ archive =~ ^${item}.*$ ]]
+  if [[ "$item" ]] && [[ archive =~ ^${item}.*$ ]]
+  then
+    notefilepath=$TODO_NOTE_ARCHIVE
+  else
+    getnotenamefromnumber "$1"
+
+    if [ "$notename" ]
     then
-        notefilepath=$TODO_NOTE_ARCHIVE
+      notefilepath="$TODO_NOTES_DIR/${notename}"
     else
-        getnotenamefromnumber $1
-
-        if [ $notename ]
-        then
-            notefilepath="$TODO_NOTES_DIR/${notename}"
-        else
-            die "TODO: Task $item has no note."
-        fi
+      die "TODO: Task $item has no note."
     fi
+  fi
 }
 
 if [ "$1" = "usage" ]
 then
-    usage
-    exit 0
+  usage
+  exit 0
 fi
 
 shift
@@ -86,66 +86,68 @@ shift
 
 case "$TODO_NOTE_ACTION" in
 "add" | "a")
-    errmsg="usage: $TODO_SH $(basename $0) $TODO_NOTE_ACTION ITEM#"
-    getnotenamefromnumber $1
+  errmsg="usage: $TODO_SH $(basename "$0") $TODO_NOTE_ACTION ITEM#"
+  getnotenamefromnumber "$1"
 
-    [ $notename ] && die "TODO: Task $item already has a note."
-    
-    # Create notes directory if doesn't exist
-    [ -d "$TODO_NOTES_DIR" ]  || mkdir -p "$TODO_NOTES_DIR" 2> /dev/null || die "Error: $TODO_NOTES_DIR is not a directory"
+  [ "$notename" ] && die "TODO: Task $item already has a note."
 
-    # Create file
-    esctitle=$(echo ${todo} | sed "s/[ 　/\\?]/-/g" | sed "s/\(-\)\+/-/g")
-    filename=$(mktemp "$TODO_NOTES_DIR/${esctitle}-${TODO_NOTE_TEMPLATE}${TODO_NOTE_EXT}")
-    notename=$(basename "$filename")
-    title=$(echo "$todo" | sed -e "s/^\(x ....-..-.. \)\?//" -e "s/^(.) \?//")
-    echo \# $title > "$TODO_NOTES_DIR/${notename}"
+  # Create notes directory if doesn't exist
+  [ -d "$TODO_NOTES_DIR" ]  || mkdir -p "$TODO_NOTES_DIR" 2> /dev/null || die "Error: $TODO_NOTES_DIR is not a directory"
 
-    # Append note tag to task
-    sed -i $item" s/$/ ${TODO_NOTE_TAG}:$notename/" "$TODO_FILE"
+  # Create file
+  esctitle=$(echo "${todo}" | sed "s/[ 　/\\?]/-/g" | sed "s/\(-\)\+/-/g")
+  filename=$(mktemp "$TODO_NOTES_DIR/${esctitle}-${TODO_NOTE_EXT}")
+  notename=$(basename "$filename")
+  title=$(echo "$todo" | sed -e "s/^\(x ....-..-.. \)\?//" -e "s/^(.) \?//")
+  echo \# "$title" > "$TODO_NOTES_DIR/${notename}"
 
-    getTodo "$item"
-    echo $item $todo
-    echo TODO: Note added to task $item.
+  # Append note tag to task
+  sed -i "${item}" "s/$/ ${TODO_NOTE_TAG}:$notename/" "$TODO_FILE"
 
-    echo "Edit note?  (y/n)"
-    read ANSWER
-    if [ "$ANSWER" = "y" ]
-    then
-        editnote "$TODO_NOTES_DIR/${notename}"
-    fi
-    ;;
+  getTodo "$item"
+  echo "${item}" "${todo}"
+  echo TODO: Note added to task "${item}".
+
+  echo "Edit note?  (y/n)"
+  read ANSWER
+  if [ "$ANSWER" = "y" ]
+  then
+    editnote "$TODO_NOTES_DIR/${notename}"
+  fi
+  ;;
 
 "edit" | "e")
-    errmsg="usage: $TODO_SH $(basename $0) edit|e ITEM#|archive|a"
-    getnotefilepath $*
-    editnote "$notefilepath"
-    ;;
+  errmsg="usage: $TODO_SH $(basename "$0") edit|e ITEM#|archive|a"
+  getnotefilepath "$*"
+  editnote "$notefilepath"
+  ;;
 
 "show" | "s")
-    errmsg="usage: $TODO_SH $(basename $0) show|s ITEM#|archive|a"
-    getnotefilepath $*
-    cat "$notefilepath"
-    ;;
+  # shellcheck disable=SC2034
+  errmsg="usage: $TODO_SH $(basename "$0") show|s ITEM#|archive|a"
+  getnotefilepath "$*"
+  cat "$notefilepath"
+  ;;
 
 "__archive")
-    getnotenamefromtext "$*"
+  getnotenamefromtext "$*"
 
-    if [ $notename ]
-    then
-        cat "$TODO_NOTES_DIR/${notename}" >> "$TODO_NOTE_ARCHIVE"
-        echo >> "$TODO_NOTE_ARCHIVE" ## Add blank line
-        rm -f "$TODO_NOTES_DIR/${notename}"
-    fi
-    ;;
+  if [ "$notename" ]
+  then
+    cat "$TODO_NOTES_DIR/${notename}" >> "$TODO_NOTE_ARCHIVE"
+    echo >> "$TODO_NOTE_ARCHIVE" ## Add blank line
+    rm -f "$TODO_NOTES_DIR/${notename}"
+  fi
+  ;;
 
 "__rmfromtext")
-    getnotenamefromtext "$*"
-    rm -f "$TODO_NOTES_DIR/$notename"
-    ;;
+  getnotenamefromtext "$*"
+  rm -f "$TODO_NOTES_DIR/$notename"
+  ;;
 
 *)
-    usage
-    ;;
+  usage
+  ;;
 
 esac
+
